name: ehreb
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - pytorch
  - matplotlib
  - seaborn
  - lifelines
  - tqdm
  - requests
  - pip:
      - pyhealth>=0.1.0  
